### ISSUE TITLE
Storybook with Windi CSS?

### ISSUE THREAD

**Issue by annabarnes1138** [JohnCampionJr/vitesse-addons#1]
I noticed that the latest version of vitesse now uses Windi CSS instead of using Tailwind directly, but I can't seem to make it work with storybook.

I've tried adding `import 'windi.css'` to preview.js in the .storybook folder, but it won't even start up because it can't find windi.css

I've also tried adding a webpack.config.js using the [Vanilla Webpack](https://windicss.netlify.app/guide/vue.html#vanilla-webpack) example from the documentation.

**Comment by JohnCampionJr** [comment]
I'm sticking with Tailwind, so I haven't adapted the storybook plugin for Windi.  Storybook requires webpack, so you could probably get it working with Windi using Windi's Webpack plugin here:

https://github.com/windicss/vue-windicss-preprocess

**Comment by annabarnes1138** [comment]
No problem... thanks for the tip. I have a different problem when using your repo, but I'll open up a new issue and close this one.
